import { openPanel, flyQuarter } from './workspace'
import { expect, test, type Page } from '@playwright/test'

async function start(page: Page) {
  await page.goto('/')
  await page.getByTestId('seed-input').fill('modern-flow')
  await page.getByTestId('start-jet_age').click()
  await expect(page.getByTestId('map')).toBeVisible()
}
async function launch(page: Page) {
  await openPanel(page, 'desk')
  await page.getByTestId('management-brief').getByRole('button', { name: 'Compare this launch' }).first().click()
  await expect(page.getByRole('dialog', { name: /^Plan / })).toBeVisible()
  await page.getByTestId('route-setup-confirm').click()
  await expect(page.getByTestId('route-setup')).toHaveCount(0)
  await openPanel(page, 'map')
}

test('first launch, full-company planning, atomic undo and report focus', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await start(page)
  await launch(page)
  const before = await page.evaluate(() => window.__harness.getState()!.airlines[0]!.routes[0]!)
  await openPanel(page, 'routes')
  await page.getByTestId('planning-workbench').locator('summary').click()
  await page.getByLabel('plan fare', { exact: true }).selectOption('2')
  await page.getByLabel('plan service', { exact: true }).selectOption('3')
  await page.getByLabel('plan frequency', { exact: true }).fill('1')
  await page.getByRole('button', { name: 'Stage this route' }).click()
  await expect(page.getByTestId('plan-comparison')).toContainText('Airline net profit')
  expect(await page.evaluate(() => window.__harness.getState()!.airlines[0]!.routes[0]!.fareLevel)).toBe(before.fareLevel)
  await page.getByTestId('commit-plan').click()
  expect(await page.evaluate(() => window.__harness.getState()!.airlines[0]!.routes[0]!.fareLevel)).toBe(2)
  await page.getByTestId('undo-action').click()
  const restored = await page.evaluate(() => window.__harness.getState()!.airlines[0]!.routes[0]!)
  expect([restored.fareLevel, restored.serviceLevel, restored.frequency]).toEqual([before.fareLevel, before.serviceLevel, before.frequency])
  await flyQuarter(page)
  await expect(page.getByRole('dialog', { name: 'Quarterly report' })).toBeVisible()
  await expect(page.getByTestId('report-card-close')).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(page.getByTestId('report-card')).toHaveCount(0)
  await expect(page.getByTestId('end-quarter')).toBeFocused()
  expect(errors).toEqual([])
})

test('display and audio preferences persist; reduced motion removes map traffic', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await start(page)
  await launch(page)
  await page.getByTestId('open-settings').click()
  await page.getByTestId('display-settings').locator('summary').click()
  await page.getByLabel('motion preference').selectOption('full')
  await expect(page.locator('.plane').first()).toBeVisible()
  await page.getByLabel('motion preference').selectOption('reduced')
  await page.getByLabel('text size').selectOption('125')
  await page.getByLabel('map traffic density').selectOption('low')
  await expect(page.locator('html')).toHaveAttribute('data-motion', 'reduced')
  await expect(page.locator('.plane')).toHaveCount(0)
  await page.getByTestId('audio-settings').locator('summary').click()
  await page.getByLabel('music volume').press('Home')
  await page.getByLabel('effects volume').press('End')
  await page.reload()
  await page.getByTestId('continue-save').click()
  await page.getByTestId('open-settings').click()
  await page.getByTestId('display-settings').locator('summary').click()
  await expect(page.getByLabel('motion preference')).toHaveValue('reduced')
  await expect(page.getByLabel('text size')).toHaveValue('125')
  await page.getByTestId('audio-settings').locator('summary').click()
  await expect(page.getByLabel('music volume')).toHaveValue('0')
  await expect(page.getByLabel('effects volume')).toHaveValue('100')
  expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(0)
})

test('map metrics, route what-ifs and optional detail are explicit', async ({ page }) => {
  await start(page)
  await launch(page)
  await page.getByLabel('map colors', { exact: true }).selectOption('profit')
  await expect(page.getByTestId('map-data-legend')).toContainText('Loss')
  await openPanel(page, 'routes')
  await expect(page.locator('.route-table').getByText('Cost/seat', { exact: true })).toBeHidden()
  await page.getByRole('button', { name: 'Show all metrics', exact: true }).click()
  await expect(page.locator('.route-table').getByText('Cost/seat', { exact: true })).toBeVisible()
  await page.locator('[data-testid^="inspect-"]').first().click()
  await page.getByTestId('closure-whatif').locator('summary').click()
  await expect(page.getByTestId('closure-whatif').locator('tbody tr')).toHaveCount(2)
  await expect(page.getByTestId('closure-whatif')).toContainText('company costs')
  await page.getByTestId('route-dossier-close').click()
})

test('maintenance and standby are deliberate fleet decisions', async ({ page }) => {
  await start(page)
  await openPanel(page, 'fleet')
  await page.locator('[data-testid^=inspect-aircraft-]').first().click()
  await page.getByLabel('Keep on standby', { exact: false }).check()
  expect(await page.evaluate(() => window.__harness.getState()!.airlines[0]!.fleet[0]!.reserve)).toBe(true)
  await page.getByRole('button', { name: /^Book maintenance/ }).click()
  await expect(page.getByTestId('operations-panel')).toContainText('In maintenance')
  await expect(page.getByRole('button', { name: /^Book maintenance/ })).toBeDisabled()
  await expect(page.getByLabel('replacement type')).toBeVisible()
})

test('short mandate starts with an established hub and declared objective', async ({ page }) => {
  await page.goto('/')
  const card = page.getByTestId('scenario-hub_defense')
  await card.getByRole('button').click()
  await card.getByRole('button').click()
  await expect(page.getByTestId('map')).toBeVisible()
  const state = await page.evaluate(() => window.__harness.getState()!)
  expect(state.scenario).toBe('hub_defense')
  expect(state.airlines[0]!.routes).toHaveLength(3)
  await openPanel(page, 'desk')
  await page.getByTestId('world-outlook').locator('summary').click()
  await expect(page.getByTestId('world-outlook')).toContainText('Airport programmes')
})
