import { test, expect } from '@playwright/test'
import { openPanel } from './workspace'

for (const width of [1440, 390]) test(`planning advice ${width}px: preview, report differences and saved expectations`, async ({ page }, info) => {
  await page.setViewportSize({ width, height: width === 1440 ? 900 : 844 })
  await page.addInitScript(() => localStorage.setItem('loadfactor:display:v1', JSON.stringify({ motion: 'reduced' })))
  await page.goto('/')
  await page.getByTestId('seed-input').fill('planning-advice')
  const scenario = page.getByTestId('scenario-hub_defense')
  await scenario.getByRole('button').click()
  await scenario.getByRole('button').click()
  await openPanel(page, 'routes')
  await page.locator('[data-testid^="inspect-"]').first().click()
  const diagnosis = page.getByTestId('route-diagnosis')
  await diagnosis.scrollIntoViewIfNeeded()
  await expect(diagnosis).toContainText('What this route needs')
  const before = await page.evaluate(() => JSON.stringify(window.__harness.getState()))
  await diagnosis.getByRole('button', { name: 'Compare improvements' }).click()
  await expect(page.getByTestId('route-recommendations')).toBeVisible()
  expect(await page.evaluate(() => JSON.stringify(window.__harness.getState()))).toBe(before)
  const preview = diagnosis.getByRole('button', { name: 'Preview this change' }).first()
  if (await preview.count()) {
    await preview.click()
    expect(await page.evaluate(() => JSON.stringify(window.__harness.getState()))).toBe(before)
    await page.getByTestId('apply-route-plan').click()
    expect(await page.evaluate(() => JSON.stringify(window.__harness.getState()))).not.toBe(before)
  }
  await page.getByTestId('end-quarter').click()
  await page.getByTestId('confirm-quarter').click()
  const report = page.getByTestId('report-card')
  await expect(report.getByTestId('plan-review')).toBeVisible()
  await expect(report.getByTestId('plan-review')).toContainText('Planned profit')
  const expected = await report.getByTestId('plan-review').innerText()
  await info.attach(`${width}-forecast-result`, { body: await page.screenshot({ animations: 'disabled' }), contentType: 'image/png' })
  await page.keyboard.press('Escape')
  await page.reload()
  await page.getByTestId('continue-save').click()
  await openPanel(page, 'report')
  await expect(page.getByTestId('plan-review')).toHaveText(expected, { useInnerText: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBe(0)
})

for (const width of [1440, 390]) test(`planning advice ${width}px: expansion comparisons, locked settings and selective apply`, async ({ page }, info) => {
  await page.setViewportSize({ width, height: width === 1440 ? 900 : 844 })
  await page.addInitScript(() => localStorage.setItem('loadfactor:display:v1', JSON.stringify({ motion: 'reduced' })))
  await page.goto('/')
  await page.getByTestId('seed-input').fill('planning-advice')
  await page.getByTestId('start-jet_age').click()
  await openPanel(page, 'routes')
  await page.getByRole('button', { name: 'Find expansion options' }).click()
  // Inspect one concrete card; comparison is read-only and its selected
  // aircraft/frequency must survive the transition into launch review.
  const card = page.getByTestId('expansion-planner').locator('article[data-testid]').first()
  await expect(card).toContainText('Company profit change/q')
  await card.getByRole('checkbox', { name: /^Compare / }).check()
  await expect(page.getByTestId('expansion-comparison')).toContainText('Under headwinds')
  await info.attach(`${width}-expansion-options`, { body: await page.screenshot({ animations: 'disabled' }), contentType: 'image/png' })
  const text = await card.innerText()
  const frame = text.match(/#(\d+)/)![1]!, frequency = text.match(/· (\d+) round trips/)![1]!
  await card.getByRole('button', { name: 'Review launch', exact: true }).click()
  await expect(page.getByTestId('route-setup-aircraft')).toHaveValue(frame)
  await expect(page.getByTestId('route-setup-freq')).toHaveText(`${frequency} rt/wk`)
  await page.getByTestId('route-setup-confirm').click()
  await expect(page.getByTestId('route-setup')).toHaveCount(0)
  const route = await page.evaluate(() => window.__harness.getState()!.airlines[0]!.routes[0]!)
  const advisor = page.getByTestId('network-advisor')
  await advisor.locator('summary').first().click()
  await advisor.getByText('Lock route settings', { exact: true }).click()
  const lock = page.getByLabel(`Lock ${route.from}-${route.to} fare`, { exact: true })
  await lock.check()
  await advisor.getByRole('button', { name: 'Find improvements', exact: true }).click()
  await expect(page.getByLabel(`Select ${route.id} fare`, { exact: true })).toHaveCount(0)
  // Make the schedule deliberately sparse, then the adviser has useful work.
  await page.evaluate(id => window.__harness.dispatch({ type: 'set_frequency', routeId: id, frequency: 1 }), route.id)
  await advisor.getByRole('button', { name: 'Find improvements', exact: true }).click()
  const advice = advisor.locator('input[aria-label^="Select "]').first()
  await expect(advice).toBeVisible()
  const before = await page.evaluate(() => JSON.stringify(window.__harness.getState()))
  await advice.check()
  await expect(page.getByTestId('adviser-comparison')).toContainText('1 selected changes')
  expect(await page.evaluate(() => JSON.stringify(window.__harness.getState()))).toBe(before)
  await info.attach(`${width}-network-adviser`, { body: await page.screenshot({ animations: 'disabled' }), contentType: 'image/png' })
  await page.getByTestId('apply-advice').click()
  expect(await page.evaluate(() => JSON.stringify(window.__harness.getState()))).not.toBe(before)
  await page.getByTestId('undo-action').click()
  expect(await page.evaluate(() => JSON.stringify(window.__harness.getState()))).toBe(before)
  await page.reload()
  await page.getByTestId('continue-save').click()
  await openPanel(page, 'routes')
  await page.getByTestId('network-advisor').locator('summary').first().click()
  await page.getByText('Lock route settings', { exact: true }).click()
  await expect(page.getByLabel(`Lock ${route.from}-${route.to} fare`, { exact: true })).toBeChecked()
  expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBe(0)
})
