import { test, expect } from '@playwright/test'
import { openPanel } from './workspace'

for (const width of [1440, 390]) test(`network operations ${width}px: trace a journey and preview a check`, async ({ page }, info) => {
  await page.setViewportSize({ width, height: width === 1440 ? 900 : 844 })
  await page.addInitScript(() => localStorage.setItem('loadfactor:display:v1', JSON.stringify({ motion:'reduced' })))
  await page.goto('/')
  const scenario=page.getByTestId('scenario-hub_defense')
  await scenario.getByRole('button').click(); await scenario.getByRole('button').click()
  await openPanel(page,'routes')
  await page.locator('[data-testid^="inspect-"]').first().click()
  await page.getByRole('button',{name:'Explore passenger flows'}).click()
  await expect(page.getByTestId('passenger-flows')).toContainText('Company journeys')
  await page.getByRole('button',{name:'Show journey on map'}).first().click()
  await expect(page.getByTestId('flow-focus')).toBeVisible()
  await expect(page.locator('.route-player.route-selected').first()).toBeVisible()
  await openPanel(page,'operations')
  await expect(page.getByTestId('operations-board')).toContainText('Aircraft and cover')
  const before=await page.evaluate(()=>JSON.stringify(window.__harness.getState()))
  await page.getByLabel('Calendar check week').selectOption('5')
  await page.getByRole('button',{name:'Preview operating change'}).click()
  await expect(page.getByTestId('operations-preview')).toContainText('Cancelled trips')
  expect(await page.evaluate(()=>JSON.stringify(window.__harness.getState()))).toBe(before)
  await page.getByRole('button',{name:'Add operating change to plan'}).click()
  await expect(page.getByTestId('plan-tray')).toBeVisible()
  await info.attach(`${width}-operations-calendar`,{body:await page.screenshot({animations:'disabled'}),contentType:'image/png'})
  await page.getByTestId('apply-shared-plan').click()
  expect(await page.evaluate(()=>JSON.stringify(window.__harness.getState()))).not.toBe(before)
  await page.getByTestId('undo-action').click()
  expect(await page.evaluate(()=>JSON.stringify(window.__harness.getState()))).toBe(before)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBe(0)
})

for (const width of [1440, 390]) test(`shared plan ${width}px: navigation, exact launch, combined apply and undo`, async ({ page }) => {
  await page.setViewportSize({ width, height: width === 1440 ? 900 : 844 })
  await page.addInitScript(() => localStorage.setItem('loadfactor:display:v1', JSON.stringify({ motion: 'reduced' })))
  await page.goto('/')
  await page.getByTestId('seed-input').fill('shared-plan-browser')
  const scenario = page.getByTestId('scenario-hub_defense')
  await scenario.getByRole('button').click(); await scenario.getByRole('button').click()
  await openPanel(page, 'routes')
  await page.locator('[data-testid^="inspect-"]').first().click()
  const before = await page.evaluate(() => JSON.stringify(window.__harness.getState()))
  await page.getByLabel('Route fare', { exact: true }).selectOption('2')
  await expect(page.getByTestId('plan-tray')).toContainText('1 planned change')
  await openPanel(page, 'fleet')
  await expect(page.getByTestId('plan-tray')).toBeVisible()
  await openPanel(page, 'routes')
  await expect(page.getByLabel('Route fare', { exact: true })).toHaveValue('2')
  expect(await page.evaluate(() => JSON.stringify(window.__harness.getState()))).toBe(before)
  await page.getByTestId('apply-shared-plan').click()
  await expect(page.getByTestId('plan-tray')).toHaveCount(0)
  await page.getByTestId('undo-action').click()
  expect(await page.evaluate(() => JSON.stringify(window.__harness.getState()))).toBe(before)
  expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBe(0)
})

for (const width of [1440, 390]) test(`capital outlook ${width}px: objective choice and capital previews are reversible`, async ({ page }) => {
  await page.setViewportSize({ width, height: width === 1440 ? 900 : 844 })
  await page.goto('/')
  const scenario = page.getByTestId('scenario-hub_defense')
  await scenario.getByRole('button').click(); await scenario.getByRole('button').click()
  const before = await page.evaluate(() => JSON.stringify(window.__harness.getState()))
  await openPanel(page, 'routes')
  await page.getByTestId('network-advisor').locator('summary').first().click()
  await page.getByLabel('Advice priority').selectOption('transfer')
  await page.getByLabel('Minimum cash reserve').fill('2')
  await openPanel(page, 'outlook')
  await expect(page.getByTestId('capital-outlook')).toContainText('Lowest cash')
  await page.getByLabel('Outlook horizon').selectOption('8')
  await page.getByText('Compare buying, leasing or waiting', { exact: true }).click()
  await page.getByRole('button', { name: 'Compare capital options' }).click()
  await expect(page.getByTestId('capital-outlook')).toContainText('Lease')
  expect(await page.evaluate(() => JSON.stringify(window.__harness.getState()))).toBe(before)
  await openPanel(page, 'routes')
  await expect(page.getByLabel('Advice priority')).toHaveValue('transfer')
  expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBe(0)
})

for (const width of [1440,390]) test(`commercial choices ${width}px: real flows, earned identity and reversible coaching`, async ({page}) => {
  await page.setViewportSize({width,height:width===1440?900:844})
  await page.addInitScript(()=>localStorage.setItem('loadfactor:display:v1',JSON.stringify({motion:'reduced',celebrations:false,quietReports:true})))
  await page.goto('/')
  const scenario=page.getByTestId('scenario-hub_defense')
  await scenario.getByRole('button').click();await scenario.getByRole('button').click()
  await page.evaluate(()=>window.__harness.endQuarter())
  await openPanel(page,'desk')
  await expect(page.getByTestId('opening-choices')).toBeVisible()
  const before=await page.evaluate(()=>JSON.stringify(window.__harness.getState()))
  await page.getByRole('button',{name:'Try: fill more seats'}).click()
  await expect(page.getByTestId('plan-tray')).toBeVisible()
  expect(await page.evaluate(()=>JSON.stringify(window.__harness.getState()))).toBe(before)
  await page.getByTestId('plan-tray').getByRole('button',{name:'1 planned change',exact:true}).click()
  await page.getByRole('button',{name:'Discard all changes'}).click()
  await openPanel(page,'finance')
  await expect(page.getByTestId('customer-identity-0')).toContainText('Earned customer preference')
  await openPanel(page,'routes');await page.locator('[data-testid^="inspect-"]').first().click()
  await page.getByRole('button',{name:'Explore passenger flows'}).click()
  await page.getByLabel('Flow period').selectOption('actual')
  await expect(page.getByTestId('passenger-flows')).toContainText('Actual journeys')
  expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBe(0)
})

test('legacy careers keep their existing availability and route totals',async({page})=>{
  await page.addInitScript(()=>localStorage.setItem('loadfactor:save:v1',JSON.stringify({version:1,scenario:'jet_age',seed:'legacy-inspection',commands:[{type:'open_route',from:'JFK',to:'ORD',aircraftId:1,frequency:5}]})))
  await page.goto('/');await page.getByTestId('continue-save').click()
  const before=await page.evaluate(()=>JSON.stringify(window.__harness.getState()))
  await openPanel(page,'operations')
  await expect(page.getByTestId('operations-board')).toContainText('earlier operations system')
  await openPanel(page,'routes');await page.locator('[data-testid^="inspect-"]').first().click()
  await expect(page.getByText('This older career records route totals only.',{exact:false})).toBeVisible()
  expect(await page.evaluate(()=>JSON.stringify(window.__harness.getState()))).toBe(before)
})
